### PR TITLE
Multi-domain support, generate SSL certs + sanity checks (PROXY-198 + PROXY-170)

### PR DESCRIPTION
**Pull request by planckadmin**
Also fix SequoiaBackend not building because Rust was complaining about dead code

### CODE REVIEW

**Comment by planckadmin** [comment]
Back to WiP. Found some remaining issues with SSL certs not being picked correctly when SNI is applied.

**Comment by dbeltra** [comment]
I built your docker locally and it doesn't run correctly because the ssl certs are missing. 

If we run the docker.run.sh copied from the example, the config is not copied into the volume but you can't see any feedback because of the `-d` flag. If you remove the flag then the feedback provided by the script is good though:

`Hostnames handled by this instance: space.separated, mx.host.name, planckproxy.company.tld, company.tld, 1.2.3.4, another.tld
  - We need certificates for the following top-level domains: host.name

Checking for existing certificate file for domain host.name
Could not find certificate file /volume/ssl/host.name.crt
Please run docker exec -it planckproxy /check.ssl.py from your Docker host to generate or renew the SSL certificate file for host.name`

When you're done I'll try it on the proxy-dev, where it should be working with the certs.

**Comment by planckadmin** [comment]
docker logs after docker run is what we usually tell customers to do. Without the -d the Proxy would just die along with the customer's SSH connection which seems imo worse than not seeing the warnings and errors without one extra command.

btw: we have to resort to this "Please run docker exec" because generating the certs requires an interactive "press ENTER" kind of shell session while the user is updating live DNS records. With the proper certbot-dns-provider plugins this could be fully automated too... or the users may still just drop their existing wildcard certs into /volume as was the initial expectation. But both these cases seem like they would be fine just hiding in documentation, no?

**Comment by dbeltra** [comment]
Oh I wasn't meaning that we should remove the `-d` I was just pointing out that removing it is the way to see the run script output. I ran the cert generation script and saw the interactive bit. I don't see a way around this either, I agree it just needs to be documented :)

**Review by dbeltra — APPROVED** [review]
yup, just tested and it works on the proxy-dev container with test@proxy.planck.dev and test@proxy2.planck.dev 👍🏻

**Pull request merged**
